# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LgLtD9zgAv5Ww3ewoZQz2T4tXwpTveOr
"""

import streamlit as st
import time

# Define the HTML for the animated loading screen
loading_html = """
<div style="display: flex; justify-content: center; align-items: center; height: 100vh;">
    <div style="text-align: center;">
        <div class="spinner"></div>
        <p style="font-size: 20px; color: #4e4e4e;">Loading, please wait...</p>
    </div>
</div>
<style>
.spinner {
  border: 8px solid #f3f3f3; /* Light grey */
  border-top: 8px solid #3498db; /* Blue */
  border-radius: 50%;
  width: 50px;
  height: 50px;
  animation: spin 1.5s linear infinite;
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
"""

# Streamlit app starts here
st.title("Streamlit App with Animated Loading Screen")

# Create a placeholder for the loading screen
placeholder = st.empty()

# Display the loading screen
placeholder.markdown(loading_html, unsafe_allow_html=True)

# Simulate loading time or data processing
time.sleep(3)  # Replace this with actual data processing logic

# Once loading is complete, clear the placeholder and display the main content
placeholder.empty()

# Main content
st.write("🎉 Welcome to the main app! This is where your content goes.")
st.line_chart([1, 2, 3, 4, 5])  # Example content